gui:
  language: "en"
  timeFormat: "01/02 15:04"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#df8e1d"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#ccd0da"
    cherryPickedCommitBgColor:
      - "#bcc0cc"
    cherryPickedCommitFgColor:
      - "#df8e1d"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#df8e1d"
  authorColors:
    "*": "#7287fd"
git:
  parseEmoji: true
  log:
    showWholeGraph: true
os:
  editPreset: "nvim"
  copyToClipboardCmd: "echo {{text}} | win32yank.exe -i"
