gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - reverse
git:
  parseEmoji: true
  log:
    showWholeGraph: true
os:
  editPreset: "nvim"
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf %s {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf %s {{text}} | base64 -w 0)\a" > /dev/tty
    fi
