gui:
  theme:
    activeBorderColor:
      - "#df8e1d"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#ccd0da"
    cherryPickedCommitBgColor:
      - "#bcc0cc"
    cherryPickedCommitFgColor:
      - "#df8e1d"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#df8e1d"
  authorColors:
    "*": "#7287fd"
  nerdFontsVersion: "3"
git:
  parseEmoji: true
  log:
    showWholeGraph: true
os:
  editPreset: "nvim"
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf %s {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf %s {{text}} | base64 -w 0)\a" > /dev/tty
    fi
